### ISSUE TITLE
Restyle homepage

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#136]
![image](https://user-images.githubusercontent.com/1611537/31580374-3a4bfe24-b14e-11e7-9606-e8b1b31f472b.png)

The homepage is the first thing that people see when they navigate to OpenDominion. In my opinion it's a bit bland and boring at the moment and I want it to leave a good (or better) impression.

I'm not a designer and I would like to have someone take a look at it and suggest (or PR) things that could be improved here.

Any additional info which could be displayed here:

- Some more explanation in text on what the game is about, how it's played etc. Feel free to use placeholder text for time being.
- Screenshots of the certain pages in the game, since the whole game is behind a login-wall.
- Current round status, like name + number and how many days are left.
- Current highscores in the round? Top X players/realms on land size/networth etc.
- Perhaps more? Feel free to ask or suggest.

Brainstorming out loud, perhaps a 9-3 column setup, where on the right there could be some info boxes regarding the current round and a basic current round highscore list or important events below it?

Here are some examples how other projects in the same PBBG genre do it:

- [Dominion](https://dominion.lykanthropos.com/www.kamikazegames.com/dominion/)
- [OGame](https://en.ogame.gameforge.com/)
- [Earth Empires](http://www.earthempires.com/)
- [Utopia](http://utopia-game.com/shared/)

(Do note that the PBBG genre itself is somewhat old and dates back before we had Bootstrap or viewport responsiveness was a thing.)

I want to keep the general style of the current [AdminLTE theme](https://adminlte.io/themes/AdminLTE/index2.html), including the colors, blue navigation bar at the top and the links in it. The content area (logo and 'Welcome to OpenDominion'-box) can be completely restyled if needed. Preferably with elements and components that AdminLTE brings.

And I know using a dashboard theme for this isn't the best idea, but it works pretty well for me for the most part. If you have any suggestions, feel free to share!

**Comment by m0nt3-q** [comment]
i have some ideas for this.

**Comment by WaveHack** [comment]
Hey @m0nt3-q, any updates on this by any chance?
