### ISSUE TITLE
User inactivity & dominion deletion due to inactivity

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#247]
Based on how it worked in Dominion, idea is to mark users as inactive if they haven't touched the game for 72 hours. Only monarchs (once implemented) can see which realmies are inactive.

A notification email (enabled by default) should also be sent, stating that their dominion has been marked as inactive.

After 4 more days (7 days total; 72 + 96 hours), their dominion should be eligible for automatic deletion, also with an email.

**Comment by Dr-Eki** [comment]
Inactive dominions take up valuable space in realms that could be filled by active dominions. If it's a big dominion, it can end up starving and become a hugely attractive target for attacks by other realms, giving hostile dominions an edge.

The Vacation mode described by @krzysztof-sikorski did exist in the original game. If you opted in for it, your dominion would be suspended after 12 hours. If you logged in during those 12 hours, you would have to start over again. After 12 hours, the dominion could not be attacked or any spells/ops performed on it. No production took place, and neither did the dominions starve. 

How about moving inactive dominions to realm #0 (after ample reminders)? Dominions in #0 can be attacked/opsed by everyone. #0 didn't exist in DC, but it was a thing in Liege Lord.

**Comment by internetfett** [comment]
Inactive dominions are now moved to 'The Graveyard' realm 0
