### ISSUE TITLE
Make title less clickable by accident on mobile

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#256]
### Current Behavior
Title on mobile is too easily accidentally clickable if you want to click on the hamburger menu button.

![image](https://user-images.githubusercontent.com/1611537/38308953-edbbe3ba-3818-11e8-90b5-5c5c4309a1b4.png)

### Expected Behavior
It should be less clickable by accident. Possibly adding a left+right margin to the <a>-tag so just above the hamburger menu is non-clickable space.

**Comment by andregce** [comment]
👋 Hi! I would like to work on this issue. Will submit a PR soon.

**Comment by WaveHack** [comment]
Great!
