### ISSUE TITLE
Add ability to delete one's own dominion

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#302]
Soft-delete dominion record to preserve data and relational links. Double check to make sure the tick system doesn't process soft-deleted dominions.

It should clear up the spot in the round for new players. Ideally we want to keep track of the round that the dominion was in. I.e. don't make dominions.realm_id null.

**Comment by stromblom** [comment]
So, just add a Deleted column to the dominion table, and then just check for that where we join/select?

**Comment by krzysztof-sikorski** [comment]
This is potentially a lot of places where the condition needs to be added - a lot of places that could accidentally display or process deleted dominions. Perhaps a better option would be to add a set of "archive/backup" tables (mirroring the structure of original dominion-related tables) and move dominion data there on delete, hard-deleting rows in original tables.

Those archives could also be used to store data for Valhalla pages, but that's a topic for a separate issue.

**Comment by WaveHack** [comment]
Softdeletes is functionality from laravel itself. Just add the column through a migration, add softdelete trait on the model and done. See the docs on this. 

Only where we manually build queries we need to add it. Realmfinder comes to mind

**Comment by krzysztof-sikorski** [comment]
> Softdeletes is functionality from laravel itself. Just add the column through a migration, add softdelete trait on the model and done. See the docs on this.

Nice. I did not notice that. My point is void then, please ignore it.

**Comment by internetfett** [comment]
Added abandon feature where dominion enters permanent exile after 24 hours (but does not delete data/events).
