### ISSUE TITLE
Add input max attr on improvement page

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#371]
Should be based on the current selected resource. Max attrs on inputs (and also value) needs to change or cap (respectively) if you change the resource type to invest

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by anudeep610** [comment]
can i work on this?

**Comment by internetfett** [comment]
Sure, players have also requested an option/button to set an input to that max attribute.

**Comment by anudeep610** [comment]
where can I find the improvement page in the code section?

**Comment by WaveHack** [comment]
Hi @anudeep610, you can find the improvements page Blade view here: https://github.com/WaveHack/OpenDominion/blob/develop/app/resources/views/pages/dominion/improvements.blade.php
