### ISSUE TITLE
Add JSON export/dump to op center show page

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#453]
See https://github.com/WaveHack/OpenDominion/issues/453#issuecomment-483828600 for details

**Comment by sandervankasteel** [comment]
@WaveHack can you expand on this issue ? Maybe I want to implement this feature

**Comment by stromblom** [comment]
It will probably just be a dump of the data as JSON, so it is easy to past i into tools. And you don't have to handle different browsers formatting of text.

**Comment by WaveHack** [comment]
Will do tonight, Sander

slz: I need to give him a quick rundown of the relevant business logic first.

**Comment by WaveHack** [comment]
Okay so we briefly talked about it this afternoon.

The Op Center page shows results (snapshots) from recent info-gathering operations (both through magic and espionage), which is used to identify potential targets to invade, before actually invading.

Currently people need to calculate the target's DP (defensive power) manually, with a combination of things like Clear Sight, Barracks Spy, Revelation and more ops. This is leading to people constructing their own 'dp calculators'.

Back in the original Dominion those tools were quite established and used throughout the playerbase. But with the death of the original game these tools also died out. Either typing relevant numbers over (units, Ares' Call spell active or not, buildings, target race etc etc), or copying and pasting text from the table and importing them in some Excel sheet or custom PHP app to process this data (and calculate DP) was common place.

A DP calc feature has been planned for OD, but has currently low priority. In order to help people with DP calcing, I would like to see an export of the op center operations, preferably in JSON format.

With regards to tech, the ops are stored in the InfoOp model (see migration or database inspection for fields). The 'data' array property contains the most relevant data that people will need to build and use these custom DP-calculator tools.

For JSON file format, I'd like to see something along the lines of:

```json5
{
  "target": {
    "dominion_name": $infoOp->targetDominion->name, // string
    "realm_number": $infoOp->targetDominion->realm->number, // int
  },
  "ops": [
    {
      "type": $infoOp->type, // string
      "data": $infoOp->data, // array
      "meta": {
        "source_dominion_name": $infoOp->sourceDominion->name, // string
        "created_at": $infoOp->created_at, // datetime
        "is_stale": $infoOp->isStale(), // boolean
      }
    },
    // ... (rinse repeat for other ops)
  ]
}
```

Rough steps from the top of my head:

1) Try to get the project working locally first. Please check the [Contribution Guide](https://github.com/WaveHack/OpenDominion/blob/develop/.github/CONTRIBUTING.md#local-development) for that.

2) After that open (and immediately start) a new round with `php artisan game:round:open --now` (note to self: 1) add an --oop flag and 2) rename --realmSize to --realm-size, same with packSize)

3) Boot up webserver and register user account and register to your test round.

4) Via Tinker: Set both $round->start_date and $dominion->created_at to something like `now()->subDays(5)`, so you're out of protection (OOP) so you can perform info-gathering operations. Also give yourself some `$dominion->resource_mana` to cast spells with.

5) Create another dominion in another realm. See classes like DominionFactory and RealmFactory for this. I'm sure you'll figure it out. The new dom needs to be in a new realm, since it's realm vs realm vs realm ad infinitum; you can't spy on doms in your own realm. Set the new dom's created_at to also in the past, so they are OOP (and thus eligible as a target for info ops), too.

6) Play around with espionage and magic on the target, get a feel for it.

There needs to be a button on the Op Center page (in the info box to the right of Clear Sight) with like 'Download (JSON)'. Additionally a controller method (OpCenterController from the top of my head) and route must be created.

I think this is the gist of it. But please try to get it working locally first.

Any questions & comments, hmu.
