### ISSUE TITLE
Add --oop flag to php artisan game:round:open

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#469]
For local testing purposes, sets the $round->created_at 3 days in the past. Still need to figure out how to get new dominions made in the past too. Or a way to totally disable protection locally

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by internetfett** [comment]
Handled with --days and --hours flags
