### ISSUE TITLE
Ability to share packdetails using OS sharetray

### ISSUE THREAD

**Issue by Mullalove** [OpenDominion/OpenDominion#536]
Quality of life improvement
Allow users to share pack details using the OS share tray

## Detailed Description
This will allow users to either copy to clipboard (expecation is that the packname and pack password will be included in the clipboard extract) or share this via socials. If using a device/OS that does not have a sharetray as standard, we should offer "copy to clipboard" button to allow users to then paste elsewhere.

Copy to clipboard format (happy for suggestions about the format if more info needed)
Hey, join my pack over at https://beta.opendominion.net/dominion
Pack: <packname>
Pack password: <pack password>

## Context
Increases usability
Makes sharing pack details even easier on mobile/tablet devices

## Possible Implementation

- On the URL https://beta.opendominion.net/dominion/status, display a share button in the node that contains pack information. 

- Pressing share button will open the OS share tray, allowing user to either copy to clipboard, share via watsapp etc

- This will not be displayed in the example of a user who has not select to join

**Comment by WaveHack** [comment]
Sounds good 👍 Do you have some more (technical) information about this os sharetray functionality? I can't find much about it atm

**Comment by Mullalove** [comment]
hmmm good point, I have found the below but this suggests this feature is more browser and OS specific than I thought

https://developers.google.com/web/updates/2016/09/navigator-share 

Hopefully you understand the contents more than I do but if it is a chrome specific feature only available  on android devices it might not be worth the effort depending on what your GA data shows about audience and device types. Basically if +90% of the traffic is desktop we could scrap it.

**Comment by WaveHack** [comment]
Ah that's useful, thanks! We'll take a look at it in the near future 😃

**Comment by internetfett** [comment]
Implemented via Realm Advisors
