### ISSUE TITLE
Fix str_plural on unit names

### ISSUE THREAD

**Issue by WaveHack** [OpenDominion/OpenDominion#664]
e.g. on training alert. 'master mhieves' wtf

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Sharqy` in `#bot-spam`.

**Comment by WaveHack** [comment]
Also on:
- Recent news feed
- Espionage page upon failure

`str_plural()` takes the whole string (eg 'Master Thief') and tries to pluralize that. Need to find a way to just pluralize the last word for any given input

**Comment by SrslySirius** [comment]
You can't simply add an "s" or some arbitrary rule like that. The plural of Voodoo Mage is Voodoo Magi, for example. I think you just have to manually write in all the key:value pairs.

**Comment by WaveHack** [comment]
There's functionality provided by the framework that OD uses to help with string manipulation, including pluralizing and singularizing(?) one or more words of text; i.e. strings.

The main issue here its that it only needs to pluralize only the last word of a unit's name (if there are multiple words in a unit name, like 'Master Thief' or 'Voodoo Mage'). But it will need a sensible and reusable code solution.

**Comment by toastar** [comment]
Can we assume the last word is the one needed to be plural? 
There are weird ones in the english language like 'Attorneys General'.

It looks like the issue could be in /src/Helpers/UnitHelper.php , maybe line 179.
I was thinking from a quick and dirty php approach, something like doing an explode, use str_plural() on only the last element of the array, than implode them back into a string?

**Comment by WaveHack** [comment]
Yeah perhaps a (static?) method in UnitHelper class which does just that. I don't like repeating code like `implode(str_plural(explode()))` all over the place

**Comment by RasmusD** [comment]
I haven't tested this because I'm lazy and don't really know php nor have a good php setup with laravel yet. But this seems like what you'd want to do:
```
    public static function str_plural_compound(string $word): string
    {
        $split = explode(' ', $word);
        $pluralised = array(reset($split), str_plural(end($split)));
        return implode(' ', $pluralised);
    }
```
I'd suggest not making this local to UnitHelper but used all over instead of str_plural. This is because str_plural is used all over and it seems there's no general checking that what's passed to str_plural is a single word and not a compound word string.

**Comment by WaveHack** [comment]
Looks good. But like you mentioned please make it a global function and throw it in `app/helpers.php`

**Comment by internetfett** [comment]
fixed by new symfony version
